version: '2.2'
services:
  forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: production
    env_file: .env
    volumes:
      - $PWD:/app
      - /tmp:/secrets
    working_dir: /app
  vendor:
    extends: forwarder
    entrypoint: sh
    volumes:
      - "$PWD/vendor:/vendor"
    command:
      - "-c"
      - "cp -R /usr/local/bundle /vendor"
