version: '2.2'
services:
  pulumi:
    build:
      context: infra/
      dockerfile: pulumi.Dockerfile
    env_file: .env
    volumes:
      - $PWD/infra:/app
    working_dir: /app
  serverless:
    image: softinstigate/serverless
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    command:
      - deploy
  deploy-infra:
    extends: pulumi
    command: up
