version: '2.2'
services:
  forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: production
    env_file: .env
    volumes:
      - $PWD:/app
      - /tmp:/secrets
    working_dir: /app
  authenticate-into-gmail:
    extends: forwarder
    environment:
      CREDENTIALS_PATH: /tmp/credentials.json
      TOKEN_PATH: /tmp/tokens.yml
    volumes:
      - "${CREDENTIALS_PATH}:/tmp/credentials.json:ro"
      - "${TOKEN_PATH}:/tmp/tokens.yml"
    entrypoint:
      - ruby
      - bin/authenticate_into_gmail.rb
  vendor:
    extends: forwarder
    entrypoint: sh
    volumes:
      - "$PWD/vendor:/vendor"
    command:
      - "-c"
      - "cp -R /usr/local/bundle /vendor"
