version: '2.2'
services:
  forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: production
    env_file: .env
    volumes:
      - $PWD:/app
      - $CREDENTIALS_FILE_PATH:/tmp/credentials.json
      - $TOKEN_FILE_PATH:/tmp/tokens.yml
    working_dir: /app
  authenticate-into-gmail:
    extends: forwarder
    volumes:
      - $CREDENTIALS_FILE_PATH:/tmp/credentials.json
      - $TOKEN_FILE_PATH:/tmp/tokens.yml
    entrypoint:
      - ruby
      - bin/authenticate_into_gmail.rb
  vendor:
    extends: forwarder
    entrypoint: sh
    volumes:
      - "$PWD/vendor:/vendor"
    command:
      - "-c"
      - "cp -R /usr/local/bundle /vendor"
