version: '2.2'
services:
  pulumi:
    build:
      context: infra/
      dockerfile: pulumi.Dockerfile
    env_file: .env
    volumes:
      - $PWD/infra:/app
    working_dir: /app
  serverless:
    image: softinstigate/serverless
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
    command:
      - deploy
  awscli:
    image: anigeo/awscli
    env_file: .env
    volumes:
      - $PWD:/app
    working_dir: /app
  deploy-infra:
    extends: pulumi
    command:
      - up
      - --skip-preview
      - "-s"
      - gmail-expensify-forwarder
  deploy-infra-with-verification:
    extends: pulumi
    command:
      - up
      - "-s"
      - gmail-expensify-forwarder
  deploy-functions:
    extends: serverless
    command:
      - deploy
  monitor-functions:
    extends: serverless
    command:
      - logs
      - "-f"
      - forwarderBegin
  destroy-functions:
    extends: serverless
    command:
      - remove
