version: '3.7'
services:
  local-forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: test
    env_file: .env
    environment:
      FORWARDER_LAST_FINISHED_TIME_SECS: 1568955600
      DEBUG_MODE: "true"
      DRY_RUN: "false"
    volumes:
      - $PWD:/app
      - /tmp:/secrets
    working_dir: /app

  units:
    build:
      context: .
      args:
        ENVIRONMENT: test
    env_file: .env.test
    entrypoint: rspec
    volumes:
      - $PWD:/app
    environment:
      LOAD_PATH: "/app/spec;/app/lib"
    working_dir: /app
    command:
      - "--fail-fast"
      - "--pattern"
      - "spec/**/*_spec.rb"
  forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: test
    environment:
      DEBUG_MODE: 'true'
      GMAIL_APPLICATION_NAME: "Expensify Receipt Forwarder"
      CREDENTIALS_PATH: secrets/credentials.json
      TOKEN_PATH: secrets/token.yml
      LAST_AUTH_CODE: 4/pAE0pCtxW9TqRZHe1BKanf6BXeYZnxLDqODl5NUvzelDckP73GKC_pQ
      FORWARDER_LAST_FINISHED_TIME_SECS: 1566104400
      ENVIRONMENT: production
      TZ: CST # This must match the timezone set within Gmail.
    volumes:
      - $PWD:/app
    working_dir: /app
  serverless:
    image: softinstigate/serverless
    env_file: .env
    environment:
      SLS_DEBUG: 'false'
    volumes:
      - $PWD:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    working_dir: /app
    command:
      - invoke
      - local
      - "--docker"
      - "-f"
      - forwarderBegin
