version: '3.7'
services:
  forwarder:
    build:
      context: .
      args:
        ENVIRONMENT: production
    env_file: .env
    volumes:
      - $PWD:/app
      - /tmp:/secrets
    working_dir: /app
