---
service:
  name: gmail-to-expensify-forwarding-service

frameworkVersion: '>=1.0.0'

provider:
  name: aws
  runtime: ruby2.5
  region: ${opt:region, 'us-east-2'}
  memorySize: 128
  deploymentBucket:
    name: ${env:SERVERLESS_BUCKET_NAME}
  deploymentPrefix: serverless

package:
  include:
    - lib/**
    - bin/**
    - vendor/**
    - .env
  exclude:
    - scripts/**
    - secrets/**
    - infra/**
    - docker-compose.*

functions:
  forwarderBegin:
    handler: bin/forwarder.begin
    description: Begins scanning for and forwarding receipts.
    timeout: 60
    events:
      - schedule:
          name: gmail_receipt_check
          description: Checks for receipts
          rate: rate(1 minute)
          enabled: true
